language: node_js
node_js:
    - "node"
env:
    global:

        - PGUSER=postgres
        - PGHOST=vcm-8440.vm.duke.edu
        - PGPASSWORD=cOgride4ci
        - PGDATABASE=sku_mgmt
        - PGPORT=5432
        - HTTPS=false
        - DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_ADMINID=7
        - NODE_ENV=test
cache:
    directories:
        - "node_modules"
install:
    - npm install -g mocha
    - npm install

script:
    - npm test
