language: node_js
node_js:
    - "node"
env:
    global:

        - PGHOST=localhost
        - PGUSER=postgres
        - PGPASSWORD=
        - PGDATABASE=sku_mgmt
        - PGPORT=5432
        - HTTPS=false
        - DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_ADMINID=7
        - NODE_ENV=test
services:
    - postgresql
cache:
    directories:
        - "node_modules"
install:
    - npm install -g mocha
    - npm install

before_script:
    - psql -U postgres -f db/food.sql
script:
    - npm test
