language: node_js
node_js:
    - "node"
addons:
    postgresql: 9.6
env:
    global:

        - PGHOST=localhost
        - PGUSER=postgres
        - PGPASSWORD=
        - PGDATABASE=postgres
        - PGPORT=5432
        - HTTPS=false
        - DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_DOMAIN=cmdev.colab.duke.edu
        - REACT_APP_ADMINID=7
        - NODE_ENV=test
        - SESSION_SECRET=aert2384742el1ng0grjfliqjh
services:
    - postgresql
cache:
    directories:
        - "node_modules"
install:
    - npm install -g mocha
    - npm install

before_script:
    - psql -v tabl=postgres -f db/food.sql -U postgres
script:
    - npm test
