export const mangoal_actions = {
  MANGOAL_GET_MANGOALS: 'MANGOAL_GET_MANGOALS',
  MANGOAL_CREATE_MANGOAL: 'MANGOAL_CREATE_MANGOAL',
  MANGOAL_SET_CURRENT_MANGOAL: 'MANGOAL_SET_CURRENT_MANGOAL',
  MANGOAL_SEARCH_SKUS: 'MANGOAL_SEARCH_SKUS',
  MANGOAL_GET_PRODUCTLINES: 'MANGOAL_GET_PRODUCTLINES',
  MANGOAL_UPDATE_FILTERS: 'MANGOAL_UPDATE_FILTERS',
  MANGOAL_UPDATE_MANGOAL_SKUS: 'MANGOAL_UPDATE_MANGOAL_SKUS',
  MANGOAL_DELETE_MANGOAL: 'MANGOAL_DELETE_MANGOAL',
  MANGOAL_DELETE_MANGOAL_SKUS: 'MANGOAL_DELETE_MANGOAL_SKUS',
  MANGOAL_GET_CALCULATIONS: 'MANGOAL_GET_CALCULATIONS',
  MANGOAL_ADD_FILTER: 'MANGOAL_ADD_FILTER',
  MANGOAL_REMOVE_FILTER: 'MANGOAL_REMOVE_FILTER',
}