export const PRDLINE_ADD_PRDLINE = 'PRDLINE_ADD_PRDLINE';
export const PRDLINE_UPDATE_PRDLINE = 'PRDLINE_UPDATE_PRDLINE';
export const PRDLINE_DELETE_PRDLINE = 'PRDLINE_DELETE_PRDLINE';
export const PRDLINE_SEARCH = 'PRDLINE_SEARCH';
export const PRDLINE_NEXT_PAGE = 'PRDLINE_NEXT_PAGE';
export const PRDLINE_PREV_PAGE = 'PRDLINE_PREV_PAGE';
export const PRDLINE_CHANGE_LIMITS = 'PRDLINE_CHANGE_LIMITS';