export const PRDLINE_ADD_PRDLINE = 'PRDLINE_ADD_PRDLINE';
export const PRDLINE_UPDATE_PRDLINE = 'PRDLINE_UPDATE_PRDLINE';
export const PRDLINE_DELETE_PRDLINE = 'PRDLINE_DELETE_PRDLINE';
export const PRDLINE_SEARCH = 'PRDLINE_SEARCH';