export const SKU_DET_GET_ING = "SKU_DET_GET_ING";
export const SKU_DET_ADD_ING = "SKU_DET_ADD_ING";
export const SKU_DET_UPDATE_SKU = "SKU_DET_UPDATE_SKU";
export const SKU_DET_DELETE_SKU = "SKU_DET_DELETE_SKU";
export const SKU_DET_DELETE_ING = "SKU_DET_DELETE_ING";
export const SKU_DET_SET_SKU = "SKU_DET_SET_SKU";
export const SKU_DET_INGREDIENT_AUTOCOMPLETE = "SKU_DET_INGREDIENT_AUTOCOMPLETE";
export const SKU_DET_PRODUCT_LINE_LIST = "SKU_DET_PRODUCT_LINE_AUTOCOMPLETE";
export const SKU_DET_ADD_ING_LOCAL = "SKU_DET_ADD_ING_LOCAL"
export const SKU_DET_DELETE_ING_LOCAL = "SKU_DET_DELETE_ING_LOCAL";
export const SKU_DET_ADD_SKU = 'SKU_DET_ADD_SKU';
export const SKU_DET_ADD_ERROR = 'SKU_DET_ADD_ERROR';
export const SKU_DET_DELETE_ERROR = 'SKU_DET_DELETE_ERROR';
export const SKU_DET_SET_NEW = "SKU_DET_SET_NEW"



