export const user_actions = {
  USER_LOG_IN_ATTEMPT: 'USER_LOG_IN_ATTEMPT',
  USER_CREATE_ATTEMPT: 'USER_CREATE_ATTEMPT',
  USER_LOG_OUT: 'USER_LOG_OUT',
  USER_NETID_LOG_IN: 'USER_NETID_LOG_IN',
}