export const manline_actions = {
  MANLINE_SEARCH: "MANLINE_SEARCH",
  MANLINE_CREATE: "MANLINE_CREATE",
  MANLINE_UPDATE: "MANLINE_UPDATE",
  MANLINE_CHANGE_LIMITS: "MANLINE_CHANGE_LIMITS",
  MANLINE_NEXT_PAGE: "MANLINE_NEXT_PAGE",
  MANLINE_PREV_PAGE: "MANLINE_PREV_PAGE",
  MANLINE_DELETE: "MANLINE_DELETE",
}