export const prdline_actions = {
  PRDLINE_ADD_PRDLINE: 'PRDLINE_ADD_PRDLINE',
  PRDLINE_UPDATE_PRDLINE: 'PRDLINE_UPDATE_PRDLINE',
  PRDLINE_DELETE_PRDLINE: 'PRDLINE_DELETE_PRDLINE',
  PRDLINE_SEARCH: 'PRDLINE_SEARCH',
  PRDLINE_NEXT_PAGE: 'PRDLINE_NEXT_PAGE',
  PRDLINE_PREV_PAGE: 'PRDLINE_PREV_PAGE',
  PRDLINE_CHANGE_LIMITS: 'PRDLINE_CHANGE_LIMITS',
}