export const user_actions = {
  USER_LOG_IN_ATTEMPT: 'USER_LOG_IN_ATTEMPT',
  USER_CREATE_ATTEMPT: 'USER_CREATE_ATTEMPT',
  USER_LOG_OUT: 'USER_LOG_OUT',
  USER_NETID_LOG_IN: 'USER_NETID_LOG_IN',
  USER_SEARCH: 'USER_SEARCH',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_CHANGE_LIMITS: 'USER_CHANGE_LIMITS',
  USER_NEXT_PAGE: 'USER_NEXT_PAGE',
  USER_PREV_PAGE: 'USER_PREV_PAGE',
}